import base64
import json
import logging
import re
import threading
from langchain_core.globals import set_debug
set_debug(True)

from langchain_core.messages import HumanMessage, SystemMessage
from langgraph.graph import END, START, StateGraph, MessagesState
from langgraph.prebuilt import ToolNode

from config import get_langfuse_handler, get_llm
from services.agent_tools import (
    get_borough_crime_and_deprivation,
    get_issue_taxonomy,
    get_lsoa_crime_and_deprivation,
    list_known_boroughs,
    validate_location,
)

logger = logging.getLogger(__name__)

TOOLS = [
    get_issue_taxonomy,
    validate_location,
    list_known_boroughs,
    get_borough_crime_and_deprivation,
    get_lsoa_crime_and_deprivation,
]

SYSTEM_PROMPT = """You are a city issue identification agent for council reporting in London.

Analyze the provided image and optional text description to identify the city issue.

If a [Confirmed GPS location] block is present in the user message, treat it as authoritative.
Skip step 3 (validate_location / list_known_boroughs). If a confirmed LSOA code is provided,
call get_lsoa_crime_and_deprivation with it. Otherwise call get_borough_crime_and_deprivation
with the confirmed borough name.

Follow these steps in order:
1. Call get_issue_taxonomy() to retrieve the list of valid issue types.
2. Analyze the image and text to identify the issue type, severity, and location.
3. Call validate_location() to verify that the borough you identified is in the database.
   - If the borough is not recognised, call list_known_boroughs() to find the closest valid name.
   - Skip this step if a [Confirmed GPS location] block is present.
4. Call get_borough_crime_and_deprivation() with the borough name to retrieve crime and
   deprivation context, and use it to inform the severity score (e.g. raise severity in
   high-deprivation or high-crime areas where council response is more urgent).
   - If a confirmed LSOA code is provided, call get_lsoa_crime_and_deprivation() instead.
5. Return your final answer as a JSON object with EXACTLY these fields:
   - issue_type: slug from the taxonomy (e.g. "pothole"), or "other" if no slug matches
   - severity: integer 1-5 (1=low impact, 5=critical/urgent)
   - location: London borough name
   - description: A formatted ticket description using this exact template:
     "This is a ticket generated by SortIt AI. [1-2 sentence description of the visible issue]. It is of {priority_band} priority because [reason]."
     Use the literal string "{priority_band}" as-is — do not replace it.
     The [reason] must explain the urgency in plain English (e.g. safety risk, obstruction, environmental hazard, or contextual factors like deprivation or crime rate).
   - confidence: float 0.0-1.0 representing your certainty in the classification
   - raw_label: your own descriptive label string if issue_type is "other", otherwise null

Your FINAL message must be ONLY the JSON object with no surrounding text."""

_DEFAULT_RESULT: dict = {
    "issue_type": "other",
    "severity": 1,
    "location": "Unknown",
    "description": "Agent could not produce a structured result.",
    "confidence": 0.0,
    "raw_label": None,
}


class AgentState(MessagesState):
    issue_report: dict | None


def _build_graph():
    llm = get_llm().bind_tools(TOOLS)
    tool_node = ToolNode(TOOLS)

    def agent_node(state: AgentState) -> dict:
        response = llm.invoke(state["messages"])
        return {"messages": [response]}

    def should_continue(state: AgentState) -> str:
        last = state["messages"][-1]
        if getattr(last, "tool_calls", None):
            return "tools"
        return "parse"

    def parse_output(state: AgentState) -> dict:
        last = state["messages"][-1]
        content = last.content if isinstance(last.content, str) else ""
        match = re.search(r"\{.*\}", content, re.DOTALL)
        if match:
            try:
                parsed = json.loads(match.group())
                return {"issue_report": parsed}
            except json.JSONDecodeError:
                logger.error("Agent returned invalid JSON: %s", content[:200])
        return {"issue_report": None}

    graph = StateGraph(AgentState)
    graph.add_node("agent", agent_node)
    graph.add_node("tools", tool_node)
    graph.add_node("parse", parse_output)
    graph.add_edge(START, "agent")
    graph.add_conditional_edges("agent", should_continue, {"tools": "tools", "parse": "parse"})
    graph.add_edge("tools", "agent")
    graph.add_edge("parse", END)

    return graph.compile()


_graph = None
_graph_lock = threading.Lock()


def _get_graph():
    global _graph
    if _graph is None:
        with _graph_lock:
            if _graph is None:
                _graph = _build_graph()
    return _graph


async def run(
    image_bytes: bytes,
    text_description: str | None = None,
    borough: str | None = None,
    lsoa_code: str | None = None,
) -> dict:
    """Run the issue-identification agent on an uploaded image.

    Args:
        image_bytes: Raw bytes of the uploaded image. Must be JPEG format.
        text_description: Optional free-text description from the citizen.
        borough: Confirmed London borough name resolved from GPS coordinates.
        lsoa_code: Confirmed LSOA code resolved from GPS coordinates.

    Returns:
        A dict with keys: issue_type, severity, location, description,
        confidence, raw_label. Falls back to _DEFAULT_RESULT if the agent
        cannot produce a structured result.
    """
    b64 = base64.b64encode(image_bytes).decode()
    content: list[dict] = [
        {"type": "image_url", "image_url": {"url": f"data:image/jpeg;base64,{b64}"}}
    ]

    if borough or lsoa_code:
        lines = ["[Confirmed GPS location]"]
        if borough:
            lines.append(f"Borough: {borough}")
        if lsoa_code:
            lines.append(f"LSOA: {lsoa_code}")
        lines.append("Trust this data. Do not attempt to infer the location from the image.")
        content.insert(0, {"type": "text", "text": "\n".join(lines)})

    if text_description:
        content.append({"type": "text", "text": text_description})

    messages = [
        SystemMessage(content=SYSTEM_PROMPT),
        HumanMessage(content=content),
    ]

    config: dict = {}
    handler = get_langfuse_handler()
    if handler:
        config["callbacks"] = [handler]

    result = await _get_graph().ainvoke({"messages": messages, "issue_report": None}, config=config or None)
    issue_report = result.get("issue_report")
    return issue_report if issue_report is not None else dict(_DEFAULT_RESULT)
